

-- >>>>> TWORZENIE TABEL <<<<<


CREATE TABLE KATEGORIA (
  KATEGORIA_ID INT,
  KATEGORIA_NAZWA VARCHAR2(45 char) NOT NULL,
  OPIS VARCHAR2(45 char),
  PRIMARY KEY (KATEGORIA_ID)
);
 
CREATE TABLE KURIER (
  KURIER_ID INT,
  NAZWA_FIRMY VARCHAR2(45 char) NOT NULL,
  PRIMARY KEY (KURIER_ID)
);
 
CREATE TABLE KARTA (
  KARTA_ID INT,
  NUMER_KARTY INT NOT NULL,
  DATA_WAZNOSCI VARCHAR2(5 char) NOT NULL,
  CVV INT NOT NULL,
  IMIE VARCHAR2(45 char) NOT NULL,
  NAZWISKO VARCHAR2(45 char) NOT NULL,
  PRIMARY KEY (KARTA_ID)
);
 
CREATE TABLE KONTO (
  KONTO_ID INT,
  KARTA_ID INT,
  LOGIN VARCHAR2(45 char) NOT NULL,
  HASLO VARCHAR2(45 char) NOT NULL,
  UPRAWNIENIA VARCHAR2(45 char) NOT NULL,
  NIP VARCHAR2(45 char) NOT NULL,
  IMIE VARCHAR2(45 char) NOT NULL,
  NAZWISKO VARCHAR2(45 char) NOT NULL,
  KONTO_AKTYWNE NUMBER(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY (KONTO_ID)
);
 
CREATE TABLE PRACOWNIK (
  PRACOWNIK_ID INT,
  KONTO_ID INT,
  DATA_ZATRUDNIENIA DATE,
  DATA_ZWOLNIENIA DATE,
  PENSJA FLOAT,
  PREMIA FLOAT,
  PRIMARY KEY (PRACOWNIK_ID)
);
 
CREATE TABLE SZCZEGOLY_ZAMOWIENIA (
  SZCZEGOLY_ZAMOWIENIA_ID INT,
  KURIER_ID INT,
  KOSZT_ZAMOWIENIA FLOAT NOT NULL,
  METODA_PLATNOSCI VARCHAR2(45 char) NOT NULL,
  DATA_WYSYLKI DATE NOT NULL,
  DOKUMENT_SPRZEDAZY VARCHAR2(45 char) NOT NULL,
  PRIMARY KEY (SZCZEGOLY_ZAMOWIENIA_ID)
  
);
 
CREATE TABLE ADRES (
  ADRES_ID INT,
  KONTO_ID INT,
  MIEJSCOWOSC VARCHAR2(45 char),
  WOJEWODZTWO VARCHAR2(45 char),
  KOD_POCZTOWY VARCHAR2(45 char),
  ULICA VARCHAR2(45 char),
  NR_DOMU INT,
  NR_LOKALU INT,
  PRIMARY KEY (ADRES_ID)
);
 
CREATE TABLE KLIENT (
  KLIENT_ID INT,
  KONTO_ID INT,
  NAZWA_FIRMY VARCHAR2(45 char),
  NIP VARCHAR2(45 char),
  PRIMARY KEY (KLIENT_ID)
);
 
CREATE TABLE KONTAKT (
  KONTAKT_ID INT,
  KONTO_ID INT,
  NR_TEL VARCHAR2(45 char),
  FAX VARCHAR2(45 char),
  EMAIL VARCHAR2(45 char),
  WWW VARCHAR2(45 char),
  PRIMARY KEY (KONTAKT_ID)
);
 
CREATE TABLE DOSTAWCA (
  DOSTAWCA_ID INT,
  ADRES_ID INT,
  KONTAKT_ID INT,
  NAZWA_FIRMY VARCHAR2(45 char),
  PRIMARY KEY (DOSTAWCA_ID)
);
 
CREATE TABLE PRODUKT (
  PRODUKT_ID INT,
  DOSTAWCA_ID INT,
  KATEGORIA_ID INT,
  PRODUCENT VARCHAR2(45 char) NOT NULL,
  NUMER_KATALOGOWY VARCHAR2(45 char) NOT NULL,
  MODEL VARCHAR2(45 char),
  CENA FLOAT NOT NULL,
  CENA_PROMOCYJNA FLOAT,
  POCZATEK_PROMOCJI DATE,
  KONIEC_PROMOCJI DATE,
  SZTUK_NA_MAGAZYNIE INT NOT NULL,
  OPIS VARCHAR2(45 char),
  ZDJECIE BLOB,
  DATA_DODANIA TIMESTAMP NOT NULL,
  PRIMARY KEY (PRODUKT_ID)
);
 
CREATE TABLE PRODUKT_SZCZEGOLY (
  PRODUKT_ID INT,
  SZCZEGOLY_ZAMOWIENIA_ID INT,
  ILOSC_SZTUK INT NOT NULL
);
 
CREATE TABLE ZAMOWIENIE (
  ZAMOWIENIE_ID INT,
  SZCZEGOLY_ZAMOWIENIA_ID INT,
  KLIENT_ID INT,
  DATA_ZALOZENIA_ZAMOWIENIA DATE,
  DATA_PRZYJECIA_ZAMOWIENIA DATE,
  DATA_REALIZACJI_ZAMOWIENIA DATE,
  ZAMOWIENIE_ZAAKCEPTOWANE NUMBER(1) DEFAULT 0 NOT NULL,
  ZAPLACONO NUMBER(1) DEFAULT 0 NOT NULL,
  ZREALIZOWANO NUMBER(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY (ZAMOWIENIE_ID)
);

ALTER TABLE KONTO
ADD CONSTRAINT KONTO_KARTA_FK
  FOREIGN KEY (KARTA_ID)
  REFERENCES KARTA(KARTA_ID);

ALTER TABLE PRACOWNIK
ADD CONSTRAINT PRACOWNIK_KONTO_FK
  FOREIGN KEY (KONTO_ID)
  REFERENCES KONTO(KONTO_ID);

ALTER TABLE SZCZEGOLY_ZAMOWIENIA
ADD CONSTRAINT SZCZEGOLY_ZAMOWIENIA_KURIER_FK
  FOREIGN KEY(KURIER_ID) 
REFERENCES KURIER(KURIER_ID);

ALTER TABLE ADRES
ADD CONSTRAINT ADRES_KONTO_FK
FOREIGN KEY(KONTO_ID) 
REFERENCES KONTO(KONTO_ID);

ALTER TABLE KLIENT
ADD CONSTRAINT KLIENT_KONTO_FK
  FOREIGN KEY(KONTO_ID) 
  REFERENCES KONTO(KONTO_ID);

ALTER TABLE KONTAKT
ADD CONSTRAINT KONTAKT_KONTO_FK
  FOREIGN KEY(KONTO_ID) 
  REFERENCES KONTO(KONTO_ID);

ALTER TABLE DOSTAWCA
ADD CONSTRAINT DOSTAWCA_ADRES_FK 
  FOREIGN KEY(ADRES_ID) 
  REFERENCES ADRES(ADRES_ID)
ADD CONSTRAINT DOSTAWCA_KONTAKT_FK 
  FOREIGN KEY(KONTAKT_ID) 
  REFERENCES KONTAKT(KONTAKT_ID);

ALTER TABLE PRODUKT
ADD CONSTRAINT PRODUKT_DOSTAWCA_FK 
  FOREIGN KEY(DOSTAWCA_ID) 
  REFERENCES DOSTAWCA(DOSTAWCA_ID)
ADD CONSTRAINT KATEGORIA_KONTAKT_FK 
  FOREIGN KEY(KATEGORIA_ID) 
  REFERENCES KATEGORIA(KATEGORIA_ID);

ALTER TABLE PRODUKT_SZCZEGOLY
ADD CONSTRAINT PRODUKT_SZCZEGOLY_PRODUKT_FK 
  FOREIGN KEY(PRODUKT_ID) 
  REFERENCES PRODUKT(PRODUKT_ID)
ADD CONSTRAINT PRODUKT_SZ_ZAMOWIENIA_FK 
  FOREIGN KEY(SZCZEGOLY_ZAMOWIENIA_ID)
  REFERENCES SZCZEGOLY_ZAMOWIENIA(SZCZEGOLY_ZAMOWIENIA_ID);

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT ZAMOWIENIE_SZ_ZAMOWIENIA_FK 
  FOREIGN KEY(SZCZEGOLY_ZAMOWIENIA_ID)
  REFERENCES SZCZEGOLY_ZAMOWIENIA(SZCZEGOLY_ZAMOWIENIA_ID)
ADD CONSTRAINT ZAMOWIENIE_KLIENT_FK 
  FOREIGN KEY(KLIENT_ID) 
  REFERENCES KLIENT(KLIENT_ID);


-- >>>>> TRIGGERY <<<<<

/* AUTO INCREMENT */
CREATE SEQUENCE KATEGORIA_SEQ;
CREATE TRIGGER KATEGORIA_TRIG BEFORE INSERT ON KATEGORIA FOR EACH ROW
BEGIN
    :NEW.KATEGORIA_ID := KATEGORIA_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE KURIER_SEQ;
CREATE TRIGGER KURIER_TRIG BEFORE INSERT ON KURIER FOR EACH ROW
BEGIN
    :NEW.KURIER_ID := KURIER_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE KARTA_SEQ;
CREATE TRIGGER KARTA_TRIG BEFORE INSERT ON KARTA FOR EACH ROW
BEGIN
    :NEW.KARTA_ID := KARTA_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE KONTO_SEQ;
CREATE TRIGGER KONTO_TRIG BEFORE INSERT ON KONTO FOR EACH ROW
BEGIN
    :NEW.KONTO_ID := KONTO_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE PRACOWNIK_SEQ;
CREATE TRIGGER PRACOWNIK_TRIG BEFORE INSERT ON PRACOWNIK FOR EACH ROW
BEGIN
    :NEW.PRACOWNIK_ID := PRACOWNIK_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE SZCZEGOLY_ZAMOWIENIA_SEQ;
CREATE TRIGGER SZCZEGOLY_ZAMOWIENIA_TRIG BEFORE INSERT ON SZCZEGOLY_ZAMOWIENIA FOR EACH ROW
BEGIN
    :NEW.SZCZEGOLY_ZAMOWIENIA_ID := SZCZEGOLY_ZAMOWIENIA_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE ADRES_SEQ;
CREATE TRIGGER ADRES_TRIG BEFORE INSERT ON ADRES FOR EACH ROW
BEGIN
    :NEW.ADRES_ID := ADRES_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE KLIENT_SEQ;
CREATE TRIGGER KLIENT_TRIG BEFORE INSERT ON KLIENT FOR EACH ROW
BEGIN
    :NEW.KLIENT_ID := KLIENT_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE KONTAKT_SEQ;
CREATE TRIGGER KONTAKT_TRIG BEFORE INSERT ON KONTAKT FOR EACH ROW
BEGIN
    :NEW.KONTAKT_ID := KONTAKT_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE DOSTAWCA_SEQ;
CREATE TRIGGER DOSTAWCA_TRIG BEFORE INSERT ON DOSTAWCA FOR EACH ROW
BEGIN
    :NEW.DOSTAWCA_ID := DOSTAWCA_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE PRODUKT_SEQ;
CREATE TRIGGER PRODUKT_TRIG BEFORE INSERT ON PRODUKT FOR EACH ROW
BEGIN
    :NEW.PRODUKT_ID := PRODUKT_SEQ.NEXTVAL;
END;
/
CREATE SEQUENCE ZAMOWIENIE_SEQ;
CREATE TRIGGER ZAMOWIENIE_TRIG BEFORE INSERT ON ZAMOWIENIE FOR EACH ROW
BEGIN
    :NEW.ZAMOWIENIE_ID := ZAMOWIENIE_SEQ.NEXTVAL;
END;
/
/* DATA DODANIA PRODUKTU */
CREATE OR REPLACE TRIGGER PRODUKT_TIMESTAMP_TRIG BEFORE INSERT ON PRODUKT 
FOR EACH ROW
BEGIN
	:NEW.DATA_DODANIA := SYSDATE;
END;
/

-- >>>>> DODAWANIE ROKORDOW <<<<<


/* KATEGORIA DATA*/
---------------------
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('AKCESORIA WĘDKARSKIE');  
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('WĘDKI'); 
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('KOŁOWROTKI'); 
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('ŻYŁKI, PLECIONKI, LINKI MUCHOWE');  
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('PRZYNĘTY, ZANĘTY');  
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('HACZYKI, KOTWICZKI');  
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('SPŁAWIKI');  
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('PODPÓRKI, STANOWISKA');
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('PODBIERAKI, SIATKI, SZTYCE');
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('PONTONY, SILNIKI, AKCESORIA');
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('TORBY, POKROWCE');
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('ODZIEŻ WĘDKARSKA I DODATKI'); 
/
INSERT INTO KATEGORIA (KATEGORIA_NAZWA)
VALUES ('AKCESORIA WĘDKARSKIE'); 
/

/* KURIER DATA */
---------------------
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('UPS');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('DHL');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('DPD');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('POCZTEX ');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('FEDEX');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('HELLMANN');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('RABEN');  
/
INSERT INTO KURIER (NAZWA_FIRMY)
VALUES ('INPOST');   