--------------------------------------------------------
--  File created - wtorek-maja-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADRES
--------------------------------------------------------

  CREATE TABLE "SKLEP"."ADRES" 
   (	"ADRES_ID" NUMBER(*,0), 
	"KONTO_ID" NUMBER(*,0), 
	"MIEJSCOWOSC" VARCHAR2(45 BYTE), 
	"WOJEWODZTWO" VARCHAR2(45 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(45 BYTE), 
	"ULICA" VARCHAR2(45 BYTE), 
	"NR_DOMU" NUMBER(*,0), 
	"NR_LOKALU" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOSTAWCA
--------------------------------------------------------

  CREATE TABLE "SKLEP"."DOSTAWCA" 
   (	"DOSTAWCA_ID" NUMBER(*,0), 
	"ADRES_ID" NUMBER(*,0), 
	"KONTAKT_ID" NUMBER(*,0), 
	"NAZWA_FIRMY" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KARTA
--------------------------------------------------------

  CREATE TABLE "SKLEP"."KARTA" 
   (	"KARTA_ID" NUMBER(*,0), 
	"NUMER_KARTY" NUMBER(*,0), 
	"DATA_WAZNOSCI" VARCHAR2(5 BYTE), 
	"CVV" NUMBER(*,0), 
	"IMIE" VARCHAR2(45 BYTE), 
	"NAZWISKO" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KATEGORIA
--------------------------------------------------------

  CREATE TABLE "SKLEP"."KATEGORIA" 
   (	"KATEGORIA_ID" NUMBER(*,0), 
	"KATEGORIA_NAZWA" VARCHAR2(45 BYTE), 
	"OPIS" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KLIENT
--------------------------------------------------------

  CREATE TABLE "SKLEP"."KLIENT" 
   (	"KLIENT_ID" NUMBER(*,0), 
	"KONTO_ID" NUMBER(*,0), 
	"NAZWA_FIRMY" VARCHAR2(45 BYTE), 
	"NIP" VARCHAR2(45 BYTE), 
	"IMIE" VARCHAR2(45 BYTE), 
	"NAZWISKO" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KONTAKT
--------------------------------------------------------

  CREATE TABLE "SKLEP"."KONTAKT" 
   (	"KONTAKT_ID" NUMBER(*,0), 
	"KONTO_ID" NUMBER(*,0), 
	"NR_TEL" VARCHAR2(45 BYTE), 
	"FAX" VARCHAR2(45 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"WWW" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KONTO
--------------------------------------------------------

  CREATE TABLE "SKLEP"."KONTO" 
   (	"KONTO_ID" NUMBER(*,0), 
	"KARTA_ID" NUMBER(*,0), 
	"LOGIN" VARCHAR2(45 BYTE), 
	"HASLO" VARCHAR2(45 BYTE), 
	"UPRAWNIENIA" VARCHAR2(45 BYTE), 
	"NIP" VARCHAR2(45 BYTE), 
	"IMIE" VARCHAR2(45 BYTE), 
	"NAZWISKO" VARCHAR2(45 BYTE), 
	"KONTO_AKTYWNE" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KURIER
--------------------------------------------------------

  CREATE TABLE "SKLEP"."KURIER" 
   (	"KURIER_ID" NUMBER(*,0), 
	"NAZWA_FIRMY" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK
--------------------------------------------------------

  CREATE TABLE "SKLEP"."PRACOWNIK" 
   (	"PRACOWNIK_ID" NUMBER(*,0), 
	"KONTO_ID" NUMBER(*,0), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"NAZWISKO" VARCHAR2(45 BYTE), 
	"PENSJA" FLOAT(126), 
	"PREMIA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUKT
--------------------------------------------------------

  CREATE TABLE "SKLEP"."PRODUKT" 
   (	"PRODUKT_ID" NUMBER(*,0), 
	"DOSTAWCA_ID" NUMBER(*,0), 
	"KATEGORIA_ID" NUMBER(*,0), 
	"PRODUCENT" VARCHAR2(45 BYTE), 
	"NUMER_KATALOGOWY" VARCHAR2(45 BYTE), 
	"MODEL" VARCHAR2(45 BYTE), 
	"CENA" FLOAT(126), 
	"CENA_PROMOCYJNA" FLOAT(126), 
	"POCZATEK_PROMOCJI" DATE, 
	"KONIEC_PROMOCJI" DATE, 
	"SZTUK_NA_MAGAZYNIE" NUMBER(*,0), 
	"OPIS" VARCHAR2(300 BYTE), 
	"ZDJECIE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ZDJECIE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUKT_SZCZEGOLY
--------------------------------------------------------

  CREATE TABLE "SKLEP"."PRODUKT_SZCZEGOLY" 
   (	"PRODUKT_ID" NUMBER(*,0), 
	"SZCZEGOLY_ID" NUMBER(*,0), 
	"ILOSC_SZTUK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SZCZEGOLY_ZAMOWIENIA
--------------------------------------------------------

  CREATE TABLE "SKLEP"."SZCZEGOLY_ZAMOWIENIA" 
   (	"SZCZEGOLY_ID" NUMBER(*,0), 
	"KURIER_ID" NUMBER(*,0), 
	"KOSZT_ZAMOWIENIA" DATE, 
	"METODA_PLATNOSCI" VARCHAR2(45 BYTE), 
	"DATA_WYSYLKI" DATE, 
	"DOKUMENT_SPRZEDAZY" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE
--------------------------------------------------------

  CREATE TABLE "SKLEP"."ZAMOWIENIE" 
   (	"ZAMOWIENIE_ID" NUMBER(*,0), 
	"SZCZEGOLY_ID" NUMBER(*,0), 
	"KLIENT_ID" NUMBER(*,0), 
	"DATA_ZALOZENIA_ZAMOWIENIA" DATE, 
	"DATA_PRZYJECIA_ZAMOWIENIA" DATE, 
	"DATA_REALIZACJI_ZAMOWIENIA" DATE, 
	"ZAMOWIENIE_ZAAKCEPTOWANE" NUMBER(1,0) DEFAULT 0, 
	"ZAPLACONO" NUMBER(1,0) DEFAULT 0, 
	"ZREALIZOWANO" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SKLEP.ADRES
SET DEFINE OFF;
REM INSERTING into SKLEP.DOSTAWCA
SET DEFINE OFF;
REM INSERTING into SKLEP.KARTA
SET DEFINE OFF;
REM INSERTING into SKLEP.KATEGORIA
SET DEFINE OFF;
Insert into SKLEP.KATEGORIA (KATEGORIA_ID,KATEGORIA_NAZWA,OPIS) values ('1','WÊDKA','Opis kategorii');
REM INSERTING into SKLEP.KLIENT
SET DEFINE OFF;
REM INSERTING into SKLEP.KONTAKT
SET DEFINE OFF;
REM INSERTING into SKLEP.KONTO
SET DEFINE OFF;
Insert into SKLEP.KONTO (KONTO_ID,KARTA_ID,LOGIN,HASLO,UPRAWNIENIA,NIP,IMIE,NAZWISKO,KONTO_AKTYWNE) values ('1',null,'user','user','1','645654','MAti','dasdsa','1');
Insert into SKLEP.KONTO (KONTO_ID,KARTA_ID,LOGIN,HASLO,UPRAWNIENIA,NIP,IMIE,NAZWISKO,KONTO_AKTYWNE) values ('2',null,'user2','user2','1','432423','tatat','fafaf','1');
REM INSERTING into SKLEP.KURIER
SET DEFINE OFF;
REM INSERTING into SKLEP.PRACOWNIK
SET DEFINE OFF;
REM INSERTING into SKLEP.PRODUKT
SET DEFINE OFF;
Insert into SKLEP.PRODUKT (PRODUKT_ID,DOSTAWCA_ID,KATEGORIA_ID,PRODUCENT,NUMER_KATALOGOWY,MODEL,CENA,CENA_PROMOCYJNA,POCZATEK_PROMOCJI,KONIEC_PROMOCJI,SZTUK_NA_MAGAZYNIE,OPIS) values ('1',null,'1','NASH','FSSDTW-455','SUPER-LONG','250',null,null,null,'78','Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy.');
Insert into SKLEP.PRODUKT (PRODUKT_ID,DOSTAWCA_ID,KATEGORIA_ID,PRODUCENT,NUMER_KATALOGOWY,MODEL,CENA,CENA_PROMOCYJNA,POCZATEK_PROMOCJI,KONIEC_PROMOCJI,SZTUK_NA_MAGAZYNIE,OPIS) values ('2',null,'1','JAXON','GDFGDF-665','TERRA','199',null,null,null,'22','Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy.');
Insert into SKLEP.PRODUKT (PRODUKT_ID,DOSTAWCA_ID,KATEGORIA_ID,PRODUCENT,NUMER_KATALOGOWY,MODEL,CENA,CENA_PROMOCYJNA,POCZATEK_PROMOCJI,KONIEC_PROMOCJI,SZTUK_NA_MAGAZYNIE,OPIS) values ('3',null,'1','DAIWA','GASDGF-773','JUNGLE','450',null,null,null,'2','Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy. Tutaj krotki opis produktu z bazy.');
Insert into SKLEP.PRODUKT (PRODUKT_ID,DOSTAWCA_ID,KATEGORIA_ID,PRODUCENT,NUMER_KATALOGOWY,MODEL,CENA,CENA_PROMOCYJNA,POCZATEK_PROMOCJI,KONIEC_PROMOCJI,SZTUK_NA_MAGAZYNIE,OPIS) values ('4',null,'1','MIKADO','UNFEGG-633','TOP','220',null,null,null,'42','OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS OPIS ');
Insert into SKLEP.PRODUKT (PRODUKT_ID,DOSTAWCA_ID,KATEGORIA_ID,PRODUCENT,NUMER_KATALOGOWY,MODEL,CENA,CENA_PROMOCYJNA,POCZATEK_PROMOCJI,KONIEC_PROMOCJI,SZTUK_NA_MAGAZYNIE,OPIS) values ('5',null,'1','KORDA','FSDFSBF-745','PREMIUM','999',null,null,null,'1','Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy.');
Insert into SKLEP.PRODUKT (PRODUKT_ID,DOSTAWCA_ID,KATEGORIA_ID,PRODUCENT,NUMER_KATALOGOWY,MODEL,CENA,CENA_PROMOCYJNA,POCZATEK_PROMOCJI,KONIEC_PROMOCJI,SZTUK_NA_MAGAZYNIE,OPIS) values ('6',null,'1','NASH','GAFGSGS-885','MOETTO','680',null,null,null,'58','Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy. Inny opis z bazy.');
REM INSERTING into SKLEP.PRODUKT_SZCZEGOLY
SET DEFINE OFF;
REM INSERTING into SKLEP.SZCZEGOLY_ZAMOWIENIA
SET DEFINE OFF;
REM INSERTING into SKLEP.ZAMOWIENIE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007184
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007184" ON "SKLEP"."ADRES" ("ADRES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007190
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007190" ON "SKLEP"."DOSTAWCA" ("DOSTAWCA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007176
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007176" ON "SKLEP"."KARTA" ("KARTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007174
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007174" ON "SKLEP"."KATEGORIA" ("KATEGORIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007186
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007186" ON "SKLEP"."KLIENT" ("KLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007188
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007188" ON "SKLEP"."KONTAKT" ("KONTAKT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007178
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007178" ON "SKLEP"."KONTO" ("KONTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007175
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007175" ON "SKLEP"."KURIER" ("KURIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007180
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007180" ON "SKLEP"."PRACOWNIK" ("PRACOWNIK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007193
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007193" ON "SKLEP"."PRODUKT" ("PRODUKT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007182
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007182" ON "SKLEP"."SZCZEGOLY_ZAMOWIENIA" ("SZCZEGOLY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007201
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKLEP"."SYS_C007201" ON "SKLEP"."ZAMOWIENIE" ("ZAMOWIENIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADRES
--------------------------------------------------------

  ALTER TABLE "SKLEP"."ADRES" ADD PRIMARY KEY ("ADRES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOSTAWCA
--------------------------------------------------------

  ALTER TABLE "SKLEP"."DOSTAWCA" ADD PRIMARY KEY ("DOSTAWCA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KARTA
--------------------------------------------------------

  ALTER TABLE "SKLEP"."KARTA" ADD PRIMARY KEY ("KARTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KATEGORIA
--------------------------------------------------------

  ALTER TABLE "SKLEP"."KATEGORIA" ADD PRIMARY KEY ("KATEGORIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENT
--------------------------------------------------------

  ALTER TABLE "SKLEP"."KLIENT" ADD PRIMARY KEY ("KLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTAKT
--------------------------------------------------------

  ALTER TABLE "SKLEP"."KONTAKT" ADD PRIMARY KEY ("KONTAKT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTO
--------------------------------------------------------

  ALTER TABLE "SKLEP"."KONTO" ADD PRIMARY KEY ("KONTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SKLEP"."KONTO" MODIFY ("KONTO_AKTYWNE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURIER
--------------------------------------------------------

  ALTER TABLE "SKLEP"."KURIER" ADD PRIMARY KEY ("KURIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNIK
--------------------------------------------------------

  ALTER TABLE "SKLEP"."PRACOWNIK" ADD PRIMARY KEY ("PRACOWNIK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUKT
--------------------------------------------------------

  ALTER TABLE "SKLEP"."PRODUKT" ADD PRIMARY KEY ("PRODUKT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SZCZEGOLY_ZAMOWIENIA
--------------------------------------------------------

  ALTER TABLE "SKLEP"."SZCZEGOLY_ZAMOWIENIA" ADD PRIMARY KEY ("SZCZEGOLY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAMOWIENIE
--------------------------------------------------------

  ALTER TABLE "SKLEP"."ZAMOWIENIE" ADD PRIMARY KEY ("ZAMOWIENIE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SKLEP"."ZAMOWIENIE" MODIFY ("ZREALIZOWANO" NOT NULL ENABLE);
  ALTER TABLE "SKLEP"."ZAMOWIENIE" MODIFY ("ZAPLACONO" NOT NULL ENABLE);
  ALTER TABLE "SKLEP"."ZAMOWIENIE" MODIFY ("ZAMOWIENIE_ZAAKCEPTOWANE" NOT NULL ENABLE);
